server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ega_bank
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=UTC
    username: ega_user
    password: ega1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
         

  # Stratégie de matching (nécessaire pour Swagger/SpringDoc avec certaines versions de Boot)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Configuration de Swagger UI / OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Vos paramètres personnalisés pour JWT
jwt:
  secret: "EgaBankSecretKeyForSecurityAndJwtTokenValidation2026"
  expiration: 86400000 # 24 heures